// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Needed by `prisma migrate diff --from-migrations`, which replays the
    // migration directory into a throwaway database. Undefined unless set, so
    // ordinary commands are unaffected. Without it the schema-parity check in
    // CI can only be reproduced by pushing.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
